### ISSUE TITLE
Installer fails on windows with a NullPointerException on boot if you have an unformatted drive.

### ISSUE THREAD

**Issue by lombokissues** [rspilker/trackertest#175]
*Migrated from Google Code (issue 65)*

**Comment by lombokissues** [comment]
:bust_in_silhouette: **reinierz** &nbsp; :clock8: Nov 01, 2009 at 21:51 UTC

The NullPointerException trace is:

java.lang.NullPointerException
       at lombok.installer.EclipseFinder.findEclipseOnWindows(EclipseFinder.java:158)
       at lombok.installer.EclipseFinder.findEclipses(EclipseFinder.java:194)
       at lombok.installer.Installer$6.run(Installer.java:311)

**Comment by lombokissues** [comment]
:bust_in_silhouette: **reinierz** &nbsp; :clock8: Nov 01, 2009 at 21:52 UTC

This was reported in http://groups.google.com/group/project-
lombok/browse_thread/thread/2f4ded6c942ad0a5

It was fixed in commit 6733b1ec567ef2cc647e690f7a4fabc85a541252 and will be rolled out in v0.8.6.

**Comment by lombokissues** [comment]
:bust_in_silhouette: **reinierz** &nbsp; :clock8: Nov 01, 2009 at 23:45 UTC

Er, that'll be v0.9.0, not v0.8.6. Due to API changes that aren't compatible, we're bumping the minor version 
number.

**Comment by lombokissues** [comment]
:bust_in_silhouette: **reinierz** &nbsp; :clock8: Nov 02, 2009 at 00:11 UTC

v0.9.0 has been rolled out at this point. Go ahead and download it!

**Comment by lombokissues** [comment]
*End of migration*
